export default {
	"collapseBooleanAttributes": true,
	"collapseInlineTagWhitespace": true,
	"collapseWhitespace": true,
	"decodeEntities": true,
	"html5": true,
	"preventAttributesEscaping": true,
	"removeAttributeQuotes": true,
	"removeComments": true,
	"removeEmptyAttributes": true,
	"removeRedundantAttributes": true,
	"removeScriptTypeAttributes": true,
	"removeStyleLinkTypeAttributes": true,
	"removeTagWhitespace": true,
	"sortAttributes": true,
	"sortClassName": true,
	"trimCustomFragments": true,
	"useShortDoctype": true,
};
